### ISSUE TITLE
middle bar not moving

### ISSUE THREAD

**Issue by darkrai13** [mdnpascual/ToF-Fishing-Bot#1]
the bar is not moving i have no idea what is wrong 
![bot](https://user-images.githubusercontent.com/127887832/225101937-d88477c8-fd5b-4d62-af02-3b6f11786619.jpg)

**Comment by mdnpascual** [comment]
There should be 2 black bars at the bottom of the tool, just like in the tutorial. This screen resolution might be too small for the tool. 

Try this fix. 

1) Look for settings.json on where you put the .exe
2) Open it with notepad or any field editor
3) Look for "UpperLeftBarPoint_Y"
4) Change it from "56" to "55"
5) Save it, then reopen the tool

I took your screenshot and Y: 55 and it looks ok-ish. If it still doesn't work, I'm afraid that screen resolution is just too small unfortunately.

**Comment by mdnpascual** [comment]
Closed for Inactivity/lack of followup
