### ISSUE TITLE
When it is the first time you catch an alpha the tool stops working.

### ISSUE THREAD

**Issue by NighV** [mdnpascual/ToF-Fishing-Bot#10]
When it is the first time you catch an alpha, maybe it is because of the achieviment popping up, the tool stops working. This happened 100% of the time up until now for me when using the tool.

**Comment by mdnpascual** [comment]
I see. The account I use has all the alphas caught so I didn't catch this. 

For now, you'll just have to manually dismiss the screen when you catch a first time alpha.

You can also use the [previous version](https://github.com/mdnpascual/ToF-Fishing-Bot/releases/download/1.03/ToF_Fishing_Bot_v1_0_2_experimental.zip) but that uses mouse to dismiss and catch fish so if you want to fish while doing something on your other monitor, that version won't have that functionality.

If you did decide to use the old version. You can copy your `settings.json` file to it so you don't need to re-do the setup again

**Comment by mdnpascual** [comment]
@NighV 

I released a new build to address this issue. I just had to increase the delay before pressing the ESC key on the fish capture dialog

Try it and let me know if it fixes in your end: https://github.com/mdnpascual/ToF-Fishing-Bot/releases/download/2.1.0/ToF_Fishing_Bot_v2_1_0.zip

You can copy the `settings.json` from the previous version to this new one so you don't need to re-setup again

**Comment by NighV** [comment]
Thanks, I will go for an alpha that I haven't catched yet

**Comment by NighV** [comment]
Update: Just got a Alpha for the first and it keept working perfectly! Thanks for the update! Also u are amazing, this tool is amazing <3

**Comment by mdnpascual** [comment]
Glad to hear!

Closing as fixed
