### ISSUE TITLE
Screen capturing cannot detect pixels on second monitor

### ISSUE THREAD

**Issue by Kaillera** [mdnpascual/ToF-Fishing-Bot#11]
I usually play TOF on a second monitor. I was trying to set up the screen caps, but it only detects a pure white pixel beyond the first monitor.

![Untitled](https://user-images.githubusercontent.com/5086682/231268081-12737019-2113-45cc-8c06-fc3de880d409.png)

**Comment by mdnpascual** [comment]
ToF needs to be run on the main monitor.

**Comment by mdnpascual** [comment]
Closed for inactivity
