### ISSUE TITLE
fishing line keep left

### ISSUE THREAD

**Issue by pmdcu1502** [mdnpascual/ToF-Fishing-Bot#14]
![problem](https://user-images.githubusercontent.com/131188752/232843007-f5ee8d33-1212-4777-b693-da4e579b9080.png)
My fishing bar keep and hold on left side, how can i fix it

**Comment by mdnpascual** [comment]
I wish you could provide a full screenshot of this monitor so I can verify the XY values. 

But based on this screenshot alone, there's a something wrong with both the Middle bar and stamina setup

First: 
I'm seeing a black line at the bottom of the black bar at the bottom of the tool. This tells me that the lower right setup is wrong. Try to target Y: 241 or Y: 240. You might want to adjust the upper left to Y:235 or Y:236 but make sure you don't have the black line at the top.

Second:
You are hitting the border on the Stamina Setup. The color should be the brightest color but still the lowest possible.

Third:
I also notice that your resolution can be bigger. The tool works better the larger the resolution of the game. It's your own choice if you want to keep the game at a lower resolution, but you will get more problems the less the tool can see.

**Comment by pmdcu1502** [comment]
Thanks for your response.
My monitor resolution is 2560x1440 pixel and game is running at 1980x1080.
I will follow your feedback and reply soon.

**Comment by pmdcu1502** [comment]
![image](https://user-images.githubusercontent.com/131188752/233259838-10394dc4-e52b-4c0a-8526-f888820a5784.png)

I have tried to follow your feedback but it doesn't fix

**Comment by mdnpascual** [comment]
Hmm, this setup to looks correct. But it's still not properly seeing it.

Do you have HDR or autoHDR enabled on windows? 

The bot is seeing too much color variance and I haven't tested it with Auto HDR enabled, I think that might be the culprit.

**Comment by pmdcu1502** [comment]
yes HDR problem so i turn it off and it worked perfectly. Many thanks

**Comment by mdnpascual** [comment]
Closing as solved
