### ISSUE TITLE
about a pixel, what that mean? ty

### ISSUE THREAD

**Issue by LoserNeverFade** [mdnpascual/ToF-Fishing-Bot#15]
![Capture1](https://user-images.githubusercontent.com/131248141/233020002-f843f51e-23e6-4213-bfba-c4999bbff3ff.PNG)

**Comment by mdnpascual** [comment]
Both Upper left and lower right are set to Y:78.

There should be 5 pixels difference. Choose the UPPER LEFT and LOWER RIGHT. Look at the tutorial image closely

**Comment by LoserNeverFade** [comment]
ah, ok ty

**Comment by mdnpascual** [comment]
closed for inactivity.
