### ISSUE TITLE
capture line not following fish bar

### ISSUE THREAD

**Issue by mahadi22** [mdnpascual/ToF-Fishing-Bot#16]
windows 10 x64 22h2 19045.2846, on dx12, 1920x1080, 3 monitor, game running on main display
ryzen 7 5800x3d + 3080

the app didnt recognize the game, it says not fishing, but the bar are moving left and right, but the capture line didnt move
already try run the app as admin, please help, thank you

![image](https://user-images.githubusercontent.com/6297984/233245312-35e65506-1359-4a3c-a57c-1e668d4bcac6.png)

**Comment by mdnpascual** [comment]
Everything looks to be correctly setup so It's weird that it's not trying to move the fishing line.

The only thing I could think of is if you messed with the advanced settings, specifically the "MiddlebarColorDetectionThreshold"

If you didn't, then I have no idea what is happening. You could try recording a video to hopefully see if there's something else, but I can't think of anything else apart from the advanced settings I said above is preventing for the tool to move the fishing line to the left here.

**Comment by mahadi22** [comment]
this issue solved with new version
