### ISSUE TITLE
Suddenly jump out of the fishing screen

### ISSUE THREAD

**Issue by hughkel58** [mdnpascual/ToF-Fishing-Bot#19]
Sometimes PC or Net lag, TOF will close fishing and show Nemu.

I found this issue: 
After fish, ToF-Fishing-Bot uses "ESC" to close. Can we set KEY "ESC" to Mouse's left key?

**Comment by mdnpascual** [comment]
The old version uses mouse to dismiss and no I'm not reverting to that behaviour again. 

I've seen this before with other people with shit PCs. Increase the dismiss delay on the settings from 4000 to 10000.

**Comment by hughkel58** [comment]
Another question:
Have you ever encountered the program KEY "D" stuck, the fishing cursor ran out of the frame?

**Comment by mdnpascual** [comment]
Closed for Inactivity/lack of followup
