### ISSUE TITLE
middle (white) bar works partially

### ISSUE THREAD

**Issue by maxipon** [mdnpascual/ToF-Fishing-Bot#2]
from the screenshot, it looks like the white bar doesn't move correctly (it only move sometimes), please look at this problem
![Untitled](https://user-images.githubusercontent.com/96283289/227790025-4bcccce4-9d65-4315-8064-1344a1cc059b.png)

**Comment by mdnpascual** [comment]
only sometimes? that is weird. In the screenshot itself, the tool wants to move the cursor to the left (Left green box). I don't see anything wrong with the 2 black bars as well.

The game needs to be in focus so the tool can move the cursor. You can't unfortunately do something else (browsing the internet, etc) while the tool is running. 

If you did tab out of the game to do something and then go back to the game and the tool is not moving the cursor. Trying pressing "A" and "D" a few times to reset the state.

It could also be the case that some program is stealing focus from the game

Can you provide a video if that is not the case above?

**Comment by maxipon** [comment]
I tried to minimize the Fisherman windows, and it is looking great now. 
Although I need to test it some more, will give you an updated state soon :D

**Comment by maxipon** [comment]
https://youtu.be/fK6S7NlQSDQ
here is a video demonstrating my current setup and how it will auto fishing, please look into it

**Comment by mdnpascual** [comment]
I see something different with your video from my testing. On the very start on the fish stamina, there is a small section of blue pixels which is probably why the tool is getting confused it's time to already catch it.

I'll try to find a fix for this. Thanks for reporting

**Comment by maxipon** [comment]
do you have any temporary fix for this?

**Comment by mdnpascual** [comment]
no temp fix/workarounds. I have to fix this on the tool

**Comment by mdnpascual** [comment]
I can't replicate your game's behavior so I can't test it, but can you try this build: 
https://github.com/mdnpascual/ToF-Fishing-Bot/releases/download/1.01-experimental/ToF_Fishing_Bot_v1_0_1_experimental.zip

You can copy your settings.json from the old version and copy to the new one so u don't need to set it up again.
Let me know if this one fixed that issue so I can release a new version.

**Comment by maxipon** [comment]
I tried your updated version, it operated perfectly! I tried to afk with it for 1 hour, and it's doing good so far! tysm :D

**Comment by mdnpascual** [comment]
Glad to hear! 

Closing Issue as resolved
