### ISSUE TITLE
D key is locked

### ISSUE THREAD

**Issue by hughkel58** [mdnpascual/ToF-Fishing-Bot#20]
Have you ever encountered the program KEY "D" stuck, the fishing cursor ran out of the frame?

**Comment by mdnpascual** [comment]
if it's the same problem where your PC lags whenever you try to catch a fish. You might need to increase the Fish Capture delay. 

I've seen this with people where their laptop lags from capturing fish or dismissing the screen. This will increase your player stamina usage and might need a better fishing rod.

**Comment by mdnpascual** [comment]
Closed for Inactivity/lack of followup
