### ISSUE TITLE
after fishing once the bot auto exit the fishing menu

### ISSUE THREAD

**Issue by CoolBoyRule** [mdnpascual/ToF-Fishing-Bot#21]
after fishing once fish the bot stops and quit the fishing

**Comment by mdnpascual** [comment]
provide more info. This report is so useless.

Join [this discord server](https://discord.gg/gateoo) and look for fishing help since this looks like a user issue

**Comment by CoolBoyRule** [comment]
Sorry i got it to work you can place it as solved i forget to change it
