### ISSUE TITLE
Mouse disabled + Middle bar not detected

### ISSUE THREAD

**Issue by lucetique** [mdnpascual/ToF-Fishing-Bot#23]
My mouse got disabled while using the bot, so I basically cannot use the bot properly in game. Plus, the middle bar is not detected by the bot (eventually the A-D buttons are not working).

**Comment by mdnpascual** [comment]
Are you using the old v1.0 version?

The new 2.0 version doesn't touch or alter the mouse at all.

**Comment by lucetique** [comment]
Nope I'm currently using the latest version since I have just downloaded it yesterday after using the 1.0 for a while.
But the main issue is not about the mouse, it's about the A-D output doesn't work at all.

**Comment by mdnpascual** [comment]
record a video showing the game plus the bot in action.

**Comment by lucetique** [comment]
https://github.com/mdnpascual/ToF-Fishing-Bot/assets/135721849/3de884a4-1fed-46e5-a7d5-172b8b123afb

Here is the video

**Comment by mdnpascual** [comment]
bot works best when the game is on fullscreen or ran in a higher resolution. I see the game's FPS already chugging so I can see why you are reducing resolution.

If running the game at fullscreen makes the game's fps just really bad, then here's my suggestion based on your video:
- change lower right settings to target Y:172 or even Y:171
- fish stamina to target X: 2179 Y: 193

If the middle bad is still isn't detected after that, then that resolution is just way too small for the bot to work with.

One more thing, if you are on Windows 11, turn off auto-HDR

**Comment by lucetique** [comment]
Ah i see, i'll check my game and the bot again. Thanks a lot
