### ISSUE TITLE
status not showing

### ISSUE THREAD

**Issue by WhiteHatRabbit1** [mdnpascual/ToF-Fishing-Bot#27]
nor the bar for the app to detect the fishing, it used to work in windows 11 same version(2.2.0) now it stopped working even if i just updated it to 2.2.1

**Comment by mdnpascual** [comment]
I don't use windows 11 so I'm not sure what broke it. can you join this discord server to describe more what's happening https://discord.gg/nTYcXMQ8

**Comment by WhiteHatRabbit1** [comment]
> I don't use windows 11 so I'm not sure what broke it. can you join this discord server to describe more what's happening https://discord.gg/nTYcXMQ8

the invite doesnt work

**Comment by mdnpascual** [comment]
> > I don't use windows 11 so I'm not sure what broke it. can you join this discord server to describe more what's happening https://discord.gg/nTYcXMQ8
> 
> the invite doesnt work

try this new link https://discord.gg/PDdcxnGD
