### ISSUE TITLE
Button integration for reeling in

### ISSUE THREAD

**Issue by Jokoril** [mdnpascual/ToF-Fishing-Bot#4]
2.4 Update added a keybind for reeling in / casting the fishing rod (Default '1').
It would be nice to see it added to the tool, along with an option to rebind the key.

**Comment by mdnpascual** [comment]
Oh nice! Didn't know about this. I'll add this in

If only the "Tap Anywhere to Close" can be cleared with the keyboard, then I can fully send the outputs in the background so you don't need to have the game in focus while fishing.

**Comment by mdnpascual** [comment]
Actually pressing Esc dismisses that screen. Looks like I can send everything to keyboard now without stealing mouse

**Comment by mdnpascual** [comment]
@Fragmansas 

Using the new reel-in hotkey has been implemented. Please refer to Advanced Customization >> Button for Fish Capture on the readme to customize the hotkey if you changed it in-game
