### ISSUE TITLE
The fishing line is not on the fishing bar when moving from left to right

### ISSUE THREAD

**Issue by NighV** [mdnpascual/ToF-Fishing-Bot#7]
It's not working properly, when the bar moves from left to right it stays just outside the yellow bar, but when it moves from right to left it works perfectly. Any ideia why this is happening?

**Comment by mdnpascual** [comment]
Record a video showing both the game and the tool while fishing

**Comment by NighV** [comment]
Idk why but it's not even workin rn, I'm trying to use on my smaller monitor 1366x768. When I use on my monitor 1920x1080 it works just fine.
Video: https://youtu.be/GTsnkHV3vcc

Update: There's a windows option which increases the monitor resolution. I increased it to 2732x1536 from the previous 1366x768, and now it is working perfectly.

**Comment by mdnpascual** [comment]
It is definitely the resolution. The more pixels that tool can see, the better. 
Glad you found a solution. 

Closing as solved
