### ISSUE TITLE
Please add compilation instructions

### ISSUE THREAD

**Issue by SmolAlli** [mdnpascual/ToF-Fishing-Bot#9]
There are currently no instructions on how to compile the program from the source code. This would be appreciated.

**Comment by mdnpascual** [comment]
I have updated the main repo to link on the correct dependencies. If you have Visual Studio or Rider, it should automatically download the required dependency packages from NuGet.

Apologies it took a while before I was able to do these as I need to clear the pending PRs before I can fix it.

The only special thing that you need to know is to add the `--recurse-submocules` command when cloning. I.E. `git clone --recurse-submodules https://github.com/mdnpascual/ToF-Fishing-Bot.git`

**Comment by mdnpascual** [comment]
Closed for Inactivity/lack of followup
